spring:
  application:
    name: code_message
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/code_message
    username: "custom_user"
    password: "wasd"
  security:
    user:
      name: "user"
      password: "user"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show sql: true
        temp:
          use_jdbc_metadata_defaults: false
#flyway:
#  url: jdbc:postgres://localhost:5432/code_message
#  schemas: public
#  user: "postgres"
#  password: "123"
