spring:
  application:
    name: code_message
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/code_message}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
  security:
    user:
      name: "user"
      password: "user"
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show sql: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    baselineOnMigrate: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/code_message}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    schemas: public
jwt:
  secret: ${JWT_SECRET:"jwt_secret_key"}
